Calendar
hack4impact-uiuc/saverlife pull request #5
Opened 2020-02-16 20:41 UTC by mattwalo32

2020-02-16 20:43 UTC, SirajChokshi commented
<img width="447" alt="Screen Shot 2020-02-16 at 2 41 53 PM" src="https://user-images.githubusercontent.com/19193347/74612390-a4663900-50ca-11ea-9205-3992feb1f537.png">

2020-03-08 02:44 UTC, mattwalo32 commented
![Calendar Screen](https://user-images.githubusercontent.com/24998201/76155652-61d5c200-60b4-11ea-95c2-3ad95dfe1d35.jpg)

2020-03-08 03:21 UTC, mattwalo32 commented
![Calendar](https://user-images.githubusercontent.com/24998201/76156005-a3b53700-60b9-11ea-993a-003c09ab59e8.jpg)

2020-03-08 03:23 UTC, uawasth2 requested changes

2020-03-08 03:23 UTC, uawasth2 commented on App/Components/AddBillDialog.js
> +// /*This is an Example of PopuUp Dialog Example in React Native*/
Delete, if not being used.

2020-03-10 02:51 UTC, uawasth2 approved these changes

2020-03-10 02:53 UTC, merged